version: "3.8"

services:
  app:
    build: .
    ports:
      - "3001:4173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
